import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { GeminiService } from '../services/geminiService';
import { StorageService } from '../services/storageService';
import { AIPlanRequest, Roadmap, Task, Priority, TaskStatus } from '../types';
import { Sparkles, Clock, Target, BookOpen, Loader2, CheckCircle } from 'lucide-react';

const AIPlanner: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState(1); // 1: Input, 2: Success/Result
  const [error, setError] = useState('');

  const [formData, setFormData] = useState<AIPlanRequest>({
    goal: '',
    duration: '2 weeks',
    timePerDay: '1 hour',
    skillLevel: 'Beginner'
  });

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const plan = await GeminiService.generateLearningPlan(formData);
      
      // Convert AI Plan to App Data Structures
      const roadmapId = Date.now().toString();
      
      // 1. Create Roadmap
      const newRoadmap: Roadmap = {
        id: roadmapId,
        title: plan.roadmapTitle,
        description: plan.roadmapDescription,
        createdAt: new Date().toISOString(),
        isAiGenerated: true,
        steps: plan.steps.map((s, idx) => ({
          id: `${roadmapId}_step_${idx}`,
          title: s.title,
          description: s.description,
          completed: false,
          resources: s.suggestedResources
        }))
      };
      StorageService.saveRoadmap(newRoadmap);

      // 2. Create Tasks for Habits (optional, just adding to task list as reminders)
      plan.dailyHabits.forEach((habit, idx) => {
          StorageService.saveTask({
            id: `${Date.now()}_habit_${idx}`,
            title: `Daily Habit: ${habit}`,
            priority: Priority.HIGH,
            status: TaskStatus.TODO,
            category: 'Learning',
            dueDate: new Date().toISOString().split('T')[0],
            description: `Generated by AI for ${plan.roadmapTitle}`
          });
      });

      setStep(2);
    } catch (err) {
      console.error(err);
      setError('Failed to generate plan. Please check your API key and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white mb-4 flex items-center justify-center gap-3">
          <Sparkles className="text-indigo-500" size={32} /> AI Roadmap Generator
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400">
          Tell us what you want to learn or achieve. Gemini will build a custom roadmap for you.
        </p>
      </div>

      {step === 1 && (
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-200 dark:border-gray-700 p-8">
          <form onSubmit={handleGenerate} className="space-y-6">
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 flex items-center gap-2">
                <Target size={18} /> What is your main goal?
              </label>
              <input 
                required
                type="text" 
                placeholder="e.g., Learn React Native, Prepare for a Marathon, Write a Book"
                className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 outline-none transition-shadow"
                value={formData.goal}
                onChange={e => setFormData({...formData, goal: e.target.value})}
              />
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 flex items-center gap-2">
                  <Clock size={18} /> Time available per day?
                </label>
                <select 
                  className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white outline-none"
                  value={formData.timePerDay}
                  onChange={e => setFormData({...formData, timePerDay: e.target.value})}
                >
                  <option>30 minutes</option>
                  <option>1 hour</option>
                  <option>2 hours</option>
                  <option>4+ hours</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 flex items-center gap-2">
                  <BookOpen size={18} /> Current Skill Level?
                </label>
                <select 
                  className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white outline-none"
                  value={formData.skillLevel}
                  onChange={e => setFormData({...formData, skillLevel: e.target.value})}
                >
                  <option>Beginner</option>
                  <option>Intermediate</option>
                  <option>Advanced</option>
                </select>
              </div>
            </div>

            <div>
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">Duration Target</label>
                <input 
                  required
                  type="text" 
                  placeholder="e.g., 2 weeks, 3 months"
                  className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 outline-none"
                  value={formData.duration}
                  onChange={e => setFormData({...formData, duration: e.target.value})}
                />
            </div>

            {error && <div className="p-4 bg-red-50 text-red-600 rounded-lg">{error}</div>}

            <button 
              type="submit" 
              disabled={loading}
              className="w-full py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-bold rounded-xl hover:opacity-90 transition-opacity shadow-lg flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {loading ? <><Loader2 className="animate-spin" /> Generating Plan...</> : <><Sparkles /> Generate My Plan</>}
            </button>
          </form>
        </div>
      )}

      {step === 2 && (
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-200 dark:border-gray-700 p-10 text-center animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="w-20 h-20 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mx-auto mb-6 text-green-600">
                <CheckCircle size={40} />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">Plan Generated Successfully!</h2>
            <p className="text-gray-600 dark:text-gray-400 mb-8">
                Your roadmap has been created and saved to your dashboard. We've also added suggested daily tasks.
            </p>
            <div className="flex justify-center gap-4">
                <button onClick={() => navigate('/roadmap')} className="px-6 py-3 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 shadow-md">
                    View Roadmap
                </button>
                <button onClick={() => navigate('/dashboard')} className="px-6 py-3 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white rounded-lg font-medium hover:bg-gray-300 dark:hover:bg-gray-600">
                    Go to Dashboard
                </button>
            </div>
            <button onClick={() => setStep(1)} className="mt-6 text-indigo-500 hover:underline text-sm">Generate another plan</button>
        </div>
      )}
    </div>
  );
};

export default AIPlanner;